### ISSUE TITLE
make-examples on travis

### ISSUE THREAD

**Issue by abelsiqueira** [ufpr-opt/perprof-py#155]
@rgaiacs, I was trying to run the script on Travis, but I only got errors:
https://travis-ci.org/abelsiqueira/perprof-py/jobs/77199570

Can you see what I'm doing wrong?

**Comment by rgaiacs** [comment]
> Can you see what I'm doing wrong?

- `subprocess.CalledProcessError: Command '['pdflatex', '-interaction', 'batchmode', '-output-directory', '/home/travis/build/abelsiqueira/perprof-py/perprof/examples/plots', '/home/travis/build/abelsiqueira/perprof-py/perprof/examples/plots/abc.tex']' returned non-zero exit status 1`

  I think that you don't have the directory `/home/travis/build/abelsiqueira/perprof-py/perprof/examples/plots/` and because of it you is getting the error.

- `_tkinter.TclError: no display name and no $DISPLAY environment variable`

  This happens when you aren't running X11.

**Comment by abelsiqueira** [comment]
I create the directory `plots`, I the rest of the path is the pwd.

Do you think this if fixable?

**Comment by rgaiacs** [comment]
> Do you think this if fixable?

I will try in the evening.

**Comment by rgaiacs** [comment]
> I create the directory plots, the rest of the path is the pwd.

=)

I thought in other possible reason for the problem. You only have read access what makes sense for security reasons since someone could write a test that write the disk until it is full/damaged.

> Do you think this if fixable?

If is the lack of writing permission, probably we can't fix it. **Unfortunately** I couldn't find that information when I search for it.

**Comment by abelsiqueira** [comment]
I do have write access, I can use sudo. But I should not have to.

Abel Siqueira
sent from cell

**Comment by abelsiqueira** [comment]
Looks like the problem is that the package standalone isn't installed, and Travis uses Ubuntu 12.04.
There are 3 options:
  - Try to install standalone from CTAN (need to install dependencies)
  - Try to install all texlive
  - Try to use [this PPA](https://launchpad.net/~texlive-backports/+archive/ubuntu/ppa).

I'm trying the last one now.
